// Closed registry: every IconKey maps to a lucide icon. Because the type is a
// closed union and this is typed Record<IconKey, LucideIcon>, an unmapped key
// is a compile error, not a runtime crash.
import type { LucideIcon } from "lucide-react"
import {
  Shield,
  ChevronLeft,
  Clock,
  CheckCircle2,
  Phone,
  Mail,
  AlertCircle,
  DollarSign,
  Users,
  Heart,
  Calendar,
  Pill,
  Activity,
  ArrowRight,
  Lock,
  Star,
  TrendingDown,
  Award,
  XCircle,
  Stethoscope,
  Eye,
  Smile,
  Zap,
  Globe,
  FileText,
  Briefcase,
  Baby,
  Home,
  MapPin,
} from "lucide-react"
import type { IconKey } from "./types"

export const ICONS: Record<IconKey, LucideIcon> = {
  shield: Shield,
  chevronLeft: ChevronLeft,
  clock: Clock,
  check: CheckCircle2,
  phone: Phone,
  mail: Mail,
  alert: AlertCircle,
  dollar: DollarSign,
  users: Users,
  heart: Heart,
  calendar: Calendar,
  pill: Pill,
  activity: Activity,
  arrowRight: ArrowRight,
  lock: Lock,
  star: Star,
  trendingDown: TrendingDown,
  award: Award,
  xCircle: XCircle,
  stethoscope: Stethoscope,
  eye: Eye,
  smile: Smile,
  zap: Zap,
  globe: Globe,
  fileText: FileText,
  briefcase: Briefcase,
  baby: Baby,
  home: Home,
  mapPin: MapPin,
}
